package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/com.off-sync.platform.tokens.v1+json"
  ],
  "produces": [
    "application/com.off-sync.platform.tokens.v1+json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Off-Sync.com Platform Tokens API",
    "title": "Platform Tokens",
    "version": "0.1.0"
  },
  "paths": {
    "/": {
      "post": {
        "operationId": "createToken",
        "responses": {
          "200": {
            "description": "create a new token",
            "schema": {
              "$ref": "#/definitions/token"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "token": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "payload": {
          "type": "string"
        },
        "ttl": {
          "type": "integer",
          "format": "int64"
        }
      }
    }
  }
}`))
}
